### PR TITLE
Added the Mapping from ER Model to Relational Model

### PR DESCRIPTION
**Pull request by nileshsrivastava27**

### CODE REVIEW

**Review by Kr-Shanu — CHANGES_REQUESTED** [review]
In one of the file ER model to Relational Model, source is missing.

In the other file you have not been assigned it, since you have not requested for the file data abstraction and data independence in the issue, so i would request you to do the same.

**Comment by Kr-Shanu** [comment]
@nileshsrivastava27 please enter the issue regarding which you have done the pull request and also do mention in issue in order to be assigned to you before pulling

**Review by Kr-Shanu — APPROVED** [review]
All good, can be added in main

**Comment by nileshsrivastava27** [comment]
Edited the change requested

**Comment by Kr-Shanu** [comment]
Thanks for contributing @nileshsrivastava27

**Pull request merged**
